spring:
  profiles.active: dev
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

tenant:
  messaging:
      exchange: tenant.topic
      queue: inspection.tenant.event
      routing-key: jci.tofs.tenant.event.panel.#

bridge:
  messaging:
    exchange: bridge.topic
    queue: inspection.bridge.event
    routing-key: jci.tofs.bridge.event.panel.#

inspection:
  messaging:
    exchange: inspection.topic
    queue: inspection.event
    routing-key: jci.tofs.inspection.event.panel.#